apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: {{ template "name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "name" . }}